<?php
/*
Project: Kumbiaphp - Main Site
File: kumbiaphp.php
Created: 27/06/2012 14:12:06
*/

?>

<div id="slogan-features" class="slogan">

	<div class="container">

		<div class="span5">
			<h1>Características de KumbiaPHP Framework</h1>
			<p>KumbiaPHP Framework PHP intenta proporcionar facilidades para construir aplicaciones robustas para entornos comerciales. Esto significa que el framework es muy flexible y configurable.</p>
		</div>
	
	</div>

</div>

<div class="container">
	
	<div class="row">
	
		<div class="span3">
			<h3>Modelo de objectos y MVC</h3>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam velit urna, dapibus ut ullamcorper nec, vestibulum nec massa. Etiam nulla lacus, condimentum at pulvinar id, pharetra at urna. Donec porta congue felis, eget pellentesque metus dapibus ut. Vivamus euismod, nisl ac tincidunt vehicula, leo nibh mattis felis, sed mattis ipsum dolor at orci. Integer purus est.</p>			
		</div>
	
		<div class="span3">
			<h3>Soporte de plantillas</h3>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam velit urna, dapibus ut ullamcorper nec, vestibulum nec massa. Etiam nulla lacus, condimentum at pulvinar id, pharetra at urna. Donec porta congue felis, eget pellentesque metus dapibus ut. Vivamus euismod, nisl ac tincidunt vehicula, leo nibh mattis felis, sed mattis ipsum dolor at orci. Integer purus est.</p>	
		</div>
		
		<div class="span3">
			<h3>Scaffolding Avanzado</h3>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam velit urna, dapibus ut ullamcorper nec, vestibulum nec massa. Etiam nulla lacus, condimentum at pulvinar id, pharetra at urna. Donec porta congue felis, eget pellentesque metus dapibus ut. Vivamus euismod, nisl ac tincidunt vehicula, leo nibh mattis felis, sed mattis ipsum dolor at orci. Integer purus est.</p>			
		</div>		
		
		<div class="span3">
			<h3>Administración de Cache</h3>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam velit urna, dapibus ut ullamcorper nec, vestibulum nec massa. Etiam nulla lacus, condimentum at pulvinar id, pharetra at urna. Donec porta congue felis, eget pellentesque metus dapibus ut. Vivamus euismod, nisl ac tincidunt vehicula, leo nibh mattis felis, sed mattis ipsum dolor at orci. Integer purus est.</p>	
		</div>	
	
		<div class="span3">
			<h3>Soporte para AJAX</h3>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam velit urna, dapibus ut ullamcorper nec, vestibulum nec massa. Etiam nulla lacus, condimentum at pulvinar id, pharetra at urna. Donec porta congue felis, eget pellentesque metus dapibus ut. Vivamus euismod, nisl ac tincidunt vehicula, leo nibh mattis felis, sed mattis ipsum dolor at orci. Integer purus est.</p>
		</div>
		<div class="span3">
			<h3>Generación de Formularios</h3>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam velit urna, dapibus ut ullamcorper nec, vestibulum nec massa. Etiam nulla lacus, condimentum at pulvinar id, pharetra at urna. Donec porta congue felis, eget pellentesque metus dapibus ut. Vivamus euismod, nisl ac tincidunt vehicula, leo nibh mattis felis, sed mattis ipsum dolor at orci. Integer purus est.</p>
		</div>
		<div class="span3">
			<h3>Componentes Gráficos</h3>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam velit urna, dapibus ut ullamcorper nec, vestibulum nec massa. Etiam nulla lacus, condimentum at pulvinar id, pharetra at urna. Donec porta congue felis, eget pellentesque metus dapibus ut. Vivamus euismod, nisl ac tincidunt vehicula, leo nibh mattis felis, sed mattis ipsum dolor at orci. Integer purus est.</p>		
		</div>
		<div class="span3">
			<h3>Seguridad</h3>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam velit urna, dapibus ut ullamcorper nec, vestibulum nec massa. Etiam nulla lacus, condimentum at pulvinar id, pharetra at urna. Donec porta congue felis, eget pellentesque metus dapibus ut. Vivamus euismod, nisl ac tincidunt vehicula, leo nibh mattis felis, sed mattis ipsum dolor at orci. Integer purus est.</p>		
		</div>
	
		<div class="span3">
			<h3>y mucho más...</h3>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam velit urna, dapibus ut ullamcorper nec, vestibulum nec massa. Etiam nulla lacus, condimentum at pulvinar id, pharetra at urna. Donec porta congue felis, eget pellentesque metus dapibus ut. Vivamus euismod, nisl ac tincidunt vehicula, leo nibh mattis felis, sed mattis ipsum dolor at orci. Integer purus est.</p>
		</div>
		
	</div>
	
</div>