<?php
/*
Project: Kumbiaphp - Main Site
File: kumbiaphp.php
Created: 27/06/2012 14:12:06
*/

?>

<div id="slogan-features" class="slogan row">

	<div class="container">

		<div class="span8">
			<h1>Características de KumbiaPHP Framework</h1>
			<p>KumbiaPHP Framework PHP intenta proporcionar facilidades para construir aplicaciones robustas para entornos comerciales. Esto significa flexibilidad y alta configuración.</p>
		</div>
	
	</div>

</div>

<div class="container">
	
	<div class="row">
	
		<div class="span3">
			<h3><i class="icon icon-large icon-tasks"></i> Modelo de objetos y MVC</h3>
			<p>KumbiaPHP se basa en el patrón MVC y la abstracción de capa de base de datos para simplificar la programación</p>			
		</div>
		
		<div class="span3">
			<h3><i class="icon icon-large icon-th"></i>Scaffolding Avanzado</h3>
			<p>Mediante scaffoling el programador dispone de un sistema CRUD para los primeros estados del desarrollo de la aplicación.</p>			
		</div>		

		<div class="span3">
			<h3><i class="icon icon-large icon-table"></i>Generación de Formularios</h3>
			<p>Para agilizar los primeros estados de desarrollo KumbiaPHP puede generar de forma automáticas formularios basándose en los modelos.</p>
		</div>

		<div class="span3">
			<h3><i class="icon icon-large icon-globe"></i>Administración de Cache</h3>
			<p>Permite generar archivos en cache para una vez entrar en modo producción permitir acceder a los sitios más rápidamente.</p>	
		</div>			

	</div>
	<div class="row">
		
		<div class="span3">
			<h3><i class="icon icon-large icon-copy"></i>Soporte de plantillas</h3>
			<p>KumbiaPHP es capaz de soporta els sistema de plantillas SMARTY y también separar mediante tres niveles de vista el código HTML.</p>	
		</div>
		
		<div class="span3">
			<h3><i class="icon icon-large icon-bar-chart"></i>Componentes Gráficos</h3>
			<p>Kumbiaphp es extensible y compatible con la mayoría de herramientas gráficas y de animaciones como Jquery, Bootstrap de Twitter y Motools.</p>		
		</div>	
		
		<div class="span3">
			<h3><i class="icon icon-large icon-pencil"></i>Soporte para AJAX</h3>
			<p>KumbiaPHP dispone de librerías adaptadas para usar AJAX y basadas en Jquery</p>
		</div>		
		
		<div class="span3">
			<h3><i class="icon icon-large icon-lock"></i>Seguridad</h3>
			<p>KumbiaPHP incluye sistemas de verificación de datos de entrada, inyección SQL y muchos más para evitar intrusiones no deseadas en nuestras aplicaciones web.</p>		
		</div>

	</div>
	<div class="row">		
		
		<div class="span3">
			<h3><i class="icon icon-large icon-cogs"></i>y mucho más...</h3>
			<p>a descubrir sobre este interesante Framework. El límite lo marcas tú...</p>
		</div>
		
	</div>
	
</div>