<?php
/*
Project: Kumbiaphp - Main Site
File: kumbiaphp.php
Created: 27/06/2012 14:12:06
*/

?>

<div id="slogan-downloads" class="slogan">

	<div class="container">
		<div class="span6">
			<h1>Descargas KumbiaPHP Framework</h1>
			<p>KumbiaPHP Framework PHP intenta proporcionar facilidades para construir aplicaciones robustas para entornos comerciales. Esto significa que el framework es muy flexible y configurable.</p>
		</div>
	</div>
	
</div>

<div class="container">

	<h2>KumbiaPHP - Spirit</h2>
	<ul>
		<li>Spirit 1.0 - Beta2 <a href="">Descargar</a></li>
		<li>Spirit 1.0 - Beta1 <a href="">Descargar</a></li>
	</ul>
	
	
	<h2>KumbiaPHP - Versiones anteriores</h2>
	<ul>
		<li>KumbiaPHP 0.5 <a href="">Descargar</a></li>
		<li>KumbiaPHP 0.4.7 <a href="">Descargar</a></li>
	</ul>
	
</div>