<?php
/*
Project: Kumbiaphp - Main Site
File: kumbiaphp.php
Created: 27/06/2012 14:12:06
*/

?>


<div id="slogan-home" class="slogan">

	<div class="container">
		<div class="span5">
			<h1>KumbiaPHP por y para todos</h1>
			<p>Descarga KumbiaPHP y desarrolla aplicaciones web estables y rápidas.</p>
			<?php echo Html::link('#','Descargar Spirit 1b2','class="btn btn-large btn-warning"')?>
		</div>
	</div>
	
</div>

<div class="container">

	<div id="features" class="row">
	
		<div class="span4">
			<h3>Rápido, ligero y flexible</h3>
			<p>KumbiaPHP es un framework para aplicaciones web libre escrito en PHP5. Basado en las prácticas de desarrollo web como DRY y el Principio KISS para software comercial y educativo. Kumbiaphp fomenta la velocidad y eficiencia en la creación y mantenimiento de aplicaciones web, reemplazando tareas de codificación repetitivas por poder, control y placer.</p>  
			<p><?php echo Html::link('/','Leer más')?></p>	
		</div>
	
		<div class="span4">
			<h3>Documentación en español</h3>
			<p>Aprende y disfruta de KumbiaPHP con los múltiples tutoriales y documentación en español que hay disponibles a traves de la wiki y del API.</p>
			<p><?php echo Html::link('/','Leer más')?></p>
		
		</div>
		
		<div class="span4">
			<h3>Repositorio GitHub</h3>
			<p>Puedes descargar la última versión en desarrollo en GITHub y disponer de las últimas correcciones, cambios y mejoras..</p>
			<p><?php echo Html::link('/','Leer más')?></p>
		
		</div>
	
	
	</div>
	
</div>