<?php
/*
Project: Kumbiaphp - Main Site
File: irc.php
Created: 27/06/2012 14:13:10
*/

?>

<div id="slogan-irc" class="slogan">

	<div class="container">
		<div class="span5">
			<h1>IRC Chat</h1>
			<p>Conoce a través de nuestro IRC a más kumbieros como tú..</p>
		</div>
	</div>

</div>


<div class="container">

	<div class="row">

		<div class="span12">
			<iframe src="http://webchat.freenode.net?nick=kumbiero....&channels=kumbiaphp&prompt=1&uio=MTE9MA4c" width="100%" height="400"></iframe>
		</div>
	
	</div>

</div>


