<!DOCTYPE html>
<html lang="es">
<head>
<meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
<title>KumbiaPHP web &amp; app Framework</title>
<?php Tag::css('bootstrap') ?>
<?php Tag::css('structure') ?>
<?php Tag::css('style') ?>
<?php echo Html::includeCss() ?>
<?php echo Tag::js('jquery/jquery.min').chr(10) ?> 
<?php echo Tag::js('bootstrap/bootstrap').chr(10) ?>
</head>
<body>

<div id="header">
	<?php View::partial('main/navbar') ?>
</div>

	
	<div id="content">
	<?php View::content(); ?>
	</div>
		
	<div id="footer">
		<?php View::partial('main/footer') ?>
	</div>
                

<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "e05a5a49-dee3-49a4-9cf0-5333a28fa9a5"}); </script>
</body>
</html>
