<?php
/*
Project: Kumbiaphp - Main Site
File: footer.php
Created: 27/06/2012 14:14:38
*/

?>

<div id="footer" class="navbar navbar-fixed-bottom">
	
	<div class="container">
	
		<div class="row">
	
			<div class="span6">
				Esta web está creada con Kumbiaphp
			</div>
			
			<div class="span6" style="text-align: right">						
				<span class="st_sharethis_hcount" displayText="ShareThis"></span>
				<span class="st_facebook_hcount" displayText="Facebook"></span>
				<span class="st_twitter_hcount" displayText="Tweet"></span>
				<span class="st_googleplus_hcount" displayText="Google +"></span>
			</div>
		
		</div>
		
	</div>

</div>