<?php
/*
Project: Kumbiaphp - Main Site
File: navbar.phtml
Created: 27/06/2012 14:14:29
*/

?>


	<div id="header" class="navbar navbar-fixed-top">

		<div class="navbar-inner">
	
			<div class="container">

			<?php echo Html::link('', Html::img('kumbiaphp_2.png','KumbiaPHP Framework','width="183" height="50"'),'class="brand"') ?>
			
			<ul class="nav nav-pills pull-right">
				<li><?php echo Html::link('', 'Inicio') ?></li>
				<li><?php echo Html::link('caracteristicas', 'Características') ?></li>
				<li><?php echo Html::link('descargas', 'Descargar') ?></li>
				<li class="dropdown">
					<?php echo Html::link('#', 'Documentación','class="dropdown-toggle" data-toggle="dropdown"') ?>
					<ul class="dropdown-menu">
						<li class="nav-header">Spirit 1.0</li>
						<li><?php echo Html::link('descargas', 'Documentación') ?></li>
						<li><?php echo Html::link('descargas', 'Guía Práctica') ?></li>
						<li><?php echo Html::link('descargas', 'API') ?></li>			
						<li class="divider"><!-- DIVIDER --></li>
						<li class="nav-header">0.5</li>
						<li><?php echo Html::link('descargas', 'Documentación') ?></li>
						<li class="divider"><!-- DIVIDER --></li>
						<li><a href="http://wiki.kumbiaphp.com">Wiki</a></li>	
					</ul>
				
				
				</li>
				
				<li class="dropdown">
					<?php echo Html::link('#', 'Soporte','class="dropdown-toggle" data-toggle="dropdown"') ?>
					<ul class="dropdown-menu">
						<li><?php echo Html::link('irc', 'IRC') ?></li>					
						<li><a href="http://foro.kumbiaphp.com">Foro</a></li>
						<li><a href="https://groups.google.com/forum/?fromgroups#!forum/kumbia">Grupo Google</a></li>
					</ul>	
				</li>				
				
				<li class="dropdown">
					<?php echo Html::link('#', 'Comunidad','class="dropdown-toggle" data-toggle="dropdown"') ?>
					<ul class="dropdown-menu">
						<li><a href="http://wiki.kumbiaphp.com">Wiki</a></li>						
					</ul>	
				</li>
				
			</ul>
			
			</div>
		
		</div>
		
	</div>		
